version: '3.8'

services:
  telegram-gifts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-gifts-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Europe/Moscow  # Настройте часовой пояс по вашему усмотрению
      - DATA_DIR=/app/data  # Явно указываем путь к директории данных 